name: Backend Continuous Integration

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths: starter/backend

defaults:
  run:
    working-directory: starter/backend

jobs:
  running-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup pipenv
        run: pip install pipenv
          
      - name: Install dependancies
        run: pipenv install

      - name: Run tests
        run: pipenv run test

  running-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup pipenv
        run: pip install pipenv flake8

      - name: Install dependancies
        run: pipenv install

      - name: Run tests
        run: pipenv run lint
