name: Frontend CI
on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main
    paths: starter/frontend

defaults:
  run:
    working-directory: starter/frontend

jobs:
  running-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node 
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Use cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: install dependancies
        run: npm ci

      - name: Run tests
        run: npm test

  running-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Use cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: install dependancies
        run: npm ci

      - name: run linter
        run: npm run lint

  running-build:
    needs: [running-test, running-linter]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Use cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: install dependancies
        run: npm ci

      - name: Run test
        run: npm run test

      - name: Build Docker image
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .

      - name: Run Docker container
        run: docker run -p 3000:3000 --name mp-frontend -d mp-frontend

      - name: Check port
        run: netstat -pultn | grep 3000

      - name: Check the running application
        run: curl -vvv http://127.0.0.1:3000

      - name: Stop docker
        run: docker stop mp-frontend
