name: Frontend CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths: starter/frontend
	
defaults:
  run:
    working-directory: starter/frontend

jobs:
  running-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node 
        uses: actions/setup-node@v4
        with:
          node-version: latest
          node-version-file: starter/frontend/.nvmrc
          
      - name: install dependancies
        run: npm ci

      - name: Run tests
        run: npm test
